// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vTMWIHaNfXuYOi72FMOVoqXF3jBmC-A',
    appId: '1:524077860902:web:56fcab989b6769baed7ee7',
    messagingSenderId: '524077860902',
    projectId: 'glow-2aa42',
    authDomain: 'glow-2aa42.firebaseapp.com',
    storageBucket: 'glow-2aa42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vTMWIHaNfXuYOi72FMOVoqXF3jBmC-A',
    appId: '1:524077860902:android:4e3d9e3511797a5ded7ee7',
    messagingSenderId: '524077860902',
    projectId: 'glow-2aa42',
    storageBucket: 'glow-2aa42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vTMWIHaNfXuYOi72FMOVoqXF3jBmC-A',
    appId: '1:524077860902:ios:a9f339a917b0607fed7ee7',
    messagingSenderId: '524077860902',
    projectId: 'glow-2aa42',
    storageBucket: 'glow-2aa42.firebasestorage.app',
    iosBundleId: 'com.glowapp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vTMWIHaNfXuYOi72FMOVoqXF3jBmC-A',
    appId: '1:524077860902:ios:a9f339a917b0607fed7ee7',
    messagingSenderId: '524077860902',
    projectId: 'glow-2aa42',
    storageBucket: 'glow-2aa42.firebasestorage.app',
    iosBundleId: 'com.glowapp.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vTMWIHaNfXuYOi72FMOVoqXF3jBmC-A',
    appId: '1:524077860902:web:86bce413ba1c3124ed7ee7',
    messagingSenderId: '524077860902',
    projectId: 'glow-2aa42',
    authDomain: 'glow-2aa42.firebaseapp.com',
    storageBucket: 'glow-2aa42.firebasestorage.app',
  );
}
